[profile.default]
src = "./contracts"      
test = "./forge-tests"   
out = "./out"            
libs = ["./lib", "./node_modules"]
solc_version = "0.7.6"     

[rpc_endpoints]
mainnet = "https://mainnet.infura.io/v3/YOUR_INFURA_API_KEY"
goerli = "https://goerli.infura.io/v3/YOUR_INFURA_API_KEY"
kovan = "https://kovan.infura.io/v3/YOUR_INFURA_API_KEY"
rinkeby = "https://rinkeby.infura.io/v3/YOUR_INFURA_API_KEY"
ropsten = "https://ropsten.infura.io/v3/YOUR_INFURA_API_KEY"
arbitrum = "https://arbitrum-mainnet.infura.io/v3/YOUR_INFURA_API_KEY"
arbitrum_sepolia = "https://sepolia-rollup.arbitrum.io/rpc/"
sei = "https://sei-chain-node-url" 

