[profile.default]
src = "./contracts"      # 指定 Foundry 使用 Hardhat 的 contracts 資料夾
test = "./forge-tests"   # Foundry 測試放在單獨目錄
out = "./out"            # 編譯輸出
libs = ["./lib", "./node_modules"]
solc_version = "0.7.6"     # Solidity 編譯器版本

[rpc_endpoints]
mainnet = "https://mainnet.infura.io/v3/YOUR_INFURA_API_KEY"
goerli = "https://goerli.infura.io/v3/YOUR_INFURA_API_KEY"
kovan = "https://kovan.infura.io/v3/YOUR_INFURA_API_KEY"
rinkeby = "https://rinkeby.infura.io/v3/YOUR_INFURA_API_KEY"
ropsten = "https://ropsten.infura.io/v3/YOUR_INFURA_API_KEY"
arbitrum = "https://arbitrum-mainnet.infura.io/v3/YOUR_INFURA_API_KEY"
arbitrum_sepolia = "https://sepolia-rollup.arbitrum.io/rpc/"


